# create a github action to run the python tool yamllint

name: Yaml Lint

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install yamllint
      run: |
        pip install yamllint

    - name: Yaml Lint
      run: |
        yamllint .
