name: Yaml Lint

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Yaml Lint
      env:
        EXTRA_ARGS: ""
      run: |
        docker run -it --rm registry.gitlab.com/just-ci/images/python:slim bash -c "yamllint ${{ env.EXTRA_ARGS }} ."
